### ISSUE TITLE
Listener for save file events

### ISSUE THREAD

**Issue by alanhamlett** [devgianlu/processing-wakatime#1]
The [caretListener](https://github.com/devgianlu/processing-wakatime/blob/00c8030e30fc69ba7340b1ffcdcf9b15e7e530b3/src/main/java/xyz/gianlu/wakatime/processing/WakatimeTool.java#L44) works, but if someone enables the `Hide read-only projects` filter in their [WakaTime website prefs](https://wakatime.com/settings/preferences) then it won't actually filter anything because the `caretListener` is calling `appendHeartbeat` with hard-coded `true` for `isWrite`:
[WakatimeTool.java#L47](https://github.com/devgianlu/processing-wakatime/blob/00c8030e30fc69ba7340b1ffcdcf9b15e7e530b3/src/main/java/xyz/gianlu/wakatime/processing/WakatimeTool.java#L47)

The fix: Add a second listener for save events. The save listener also calls `appendHeartbeat` with `true` for `isWrite`, but now the `caretListener` can call `appendHeartbeat` with `false`.

**Comment by devgianlu** [comment]
I'll have to find a workaround for this because the Processing API (PDE) lacks pretty much every listener that someone would want to have.
