### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by alanhamlett** [devgianlu/processing-wakatime#2]
The original code from jetbrains-wakatime is licensed under MIT license, so the original attribution needs to be included along with your compatible license file.

**Comment by devgianlu** [comment]
I've added the `LICENSE` file. Is this enough?

**Comment by alanhamlett** [comment]
You should add a copy of the `jetbrains-wakatime` license inline in `LICENSE`, after your own code's license:
https://github.com/wakatime/jetbrains-wakatime/blob/master/LICENSE
